#! /usr/bin/env python

from collections import OrderedDict 

sample = {
    'data_obs' : {
        'order' : 0,
        'files' : ['SingleMuon_Run2015C-05Oct2015-v1', 'SingleMuon_Run2015D-05Oct2015-v1', 'SingleMuon_Run2015D-PromptReco-v4', 'SingleElectron_Run2015C-05Oct2015-v1', 'SingleElectron_Run2015D-05Oct2015-v1', 'SingleElectron_Run2015D-PromptReco-v4', 'MET_Run2015C-05Oct2015-v1', 'MET_Run2015D-05Oct2015-v1', 'MET_Run2015D-PromptReco-v4'], #'DoubleMuon_Run2015B_PromptReco_v1', 'DoubleMuon_Run2015B_17Jul2015_v1', 'DoubleEG_Run2015B_PromptReco_v1', 'DoubleEG_Run2015B_17Jul2015_v1', 
        #'files' : ['2p1fb/SingleMuon_Run2015C-05Oct2015-v1', '2p1fb/SingleMuon_Run2015D-05Oct2015-v1', '2p1fb/SingleMuon_Run2015D-PromptReco-v4', '2p1fb/SingleElectron_Run2015C-05Oct2015-v1', '2p1fb/SingleElectron_Run2015D-05Oct2015-v1', '2p1fb/SingleElectron_Run2015D-PromptReco-v4', '2p1fb/MET_Run2015C-05Oct2015-v1', '2p1fb/MET_Run2015D-05Oct2015-v1', '2p1fb/MET_Run2015D-PromptReco-v4'],
        'fillcolor' : 0,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Data",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL' : {
        'order' : 1,
        'files' : ['DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v1'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL_HT' : {
        'order' : 1,
        'files' : ['DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'DYJetsToLL_M-50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2', 'DYJetsToLL_M-50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu' : {
        'order' : 1,
        'files' : ['DYJetsToNuNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v1'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu_HT' : {
        'order' : 1,
        'files' : ['ZJetsToNuNu_HT-100To200_13TeV-madgraph-v1', 'ZJetsToNuNu_HT-200To400_13TeV-madgraph-v1', 'ZJetsToNuNu_HT-400To600_13TeV-madgraph-v1', 'ZJetsToNuNu_HT-600ToInf_13TeV-madgraph-v2'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJets_HT' : {
        'order' : 1,
        'files' : ['DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'DYJetsToLL_M-50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2', 'DYJetsToLL_M-50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'ZJetsToNuNu_HT-100To200_13TeV-madgraph-v1', 'ZJetsToNuNu_HT-200To400_13TeV-madgraph-v1', 'ZJetsToNuNu_HT-400To600_13TeV-madgraph-v1', 'ZJetsToNuNu_HT-600ToInf_13TeV-madgraph-v2'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu' : {
        'order' : 2,
        'files' : ['WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v1'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu_HT' : {
        'order' : 2,
        'files' : ['WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-400To600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-600To800_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-800To1200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-1200To2500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-2500ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],#'WJetsToLNu_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        #'files' : ['WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-400To600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'WJetsToLNu_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'TTbar' : {
        'order' : 3,
        'files' : ['TT_TuneCUETP8M1_13TeV-powheg-pythia8-ext-v1', 'TTWJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8-v1', 'TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8-v2'],
        #'files' : ['TT_TuneCUETP8M1_13TeV-powheg-pythia8-v1'],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}",#, single t
        'weight': 1.,
        'plot': True,
    },
    'ST' : {
        'order' : 4,
        'files' : ['ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1-v1', 'ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1-v1', 'ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1-v1', 'ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1-v1', 'ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1-v2'],
        'fillcolor' : 801,
        'fillstyle' : 1001,
        'linecolor' : 801,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "single t",
        'weight': 1.,
        'plot': True,
    },
    'VV' : {#'WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8-v1', 
        'order' : 5,
        'files' : ['WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZZTo2Q2Nu_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZZTo4L_13TeV-amcatnloFXFX-pythia8-v1', 'ZH_HToBB_ZToLL_M125_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZH_HToBB_ZToNuNu_M125_13TeV_amcatnloFXFX_madspin_pythia8-v1'], #'WH_HToBB_WToLNu_M125_13TeV_amcatnloFXFX_madspin_pythia8-v1'

#        'files' : ['WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZZTo2Q2Nu_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZZTo4L_13TeV-amcatnloFXFX-pythia8-v1'],

        #'files' : ['WW_TuneCUETP8M1_13TeV-pythia8-v1','WZ_TuneCUETP8M1_13TeV-pythia8-v1','ZZ_TuneCUETP8M1_13TeV-pythia8-v1', 'ZH_HToBB_ZToLL_M125_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZH_HToBB_ZToNuNu_M125_13TeV_amcatnloFXFX_madspin_pythia8-v1'],
        'fillcolor' : 602,
        'fillstyle' : 1001,
        'linecolor' : 602,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "VV, VH",
        'weight': 1.,
        'plot': True,
    },
    'QCD' : {
        'order' : 6,
        'files' : ['QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1', 'QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 921,
        'fillstyle' : 1001,
        'linecolor' : 921,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "multijet",
        'weight': 1.,
        'plot': True,
    },
    
    'AllBkg' : {
        'order' : 99,
        'files' : ['DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v1', 'DYJetsToNuNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v1', 'WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v1', 'TT_TuneCUETP8M1_13TeV-powheg-pythia8-v1', 'ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1-v1', 'ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1-v1', 'ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1-v1', 'ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1-v1', 'ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1-v2', 'WW_TuneCUETP8M1_13TeV-pythia8-v1','WZ_TuneCUETP8M1_13TeV-pythia8-v1','ZZ_TuneCUETP8M1_13TeV-pythia8-v1', 'ZH_HToBB_ZToLL_M125_13TeV_amcatnloFXFX_madspin_pythia8-v1', 'ZH_HToBB_ZToNuNu_M125_13TeV_amcatnloFXFX_madspin_pythia8-v1'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "EWK backgrounds",
        'weight': 1.,
        'plot': True,
    },
    

#################### ALL BBbarDM SCALAR

    'bbDMs_Mchi1_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1_Mphi20' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=20 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=50 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1_Mphi100' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=100 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=200 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1_Mphi300' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=300 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=500 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1_Mphi1000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=1000 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi10_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-10_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi10_Mphi100' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-10_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=100 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi10_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-10_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=50 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi150_Mphi1000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-150_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=1000 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi150_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-150_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=200 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi150_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-150_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=500 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi50_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-50_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=50 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi500_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-500_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=500 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },



    'bbDMs_Mchi1000_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1000_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=1000 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi10_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-10_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi10_Mphi15' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-10_Mphi-15_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=15 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1000_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1000_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=1000 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi1000_Mphi1000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1000_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=1000 GeV m_{#Chi}=1000 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi150_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-150_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi150_Mphi295' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-150_Mphi-295_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=295 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi50_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-50_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=5 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi50_Mphi95' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-50_Mphi-95_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=95 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi500_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-500_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi500_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-500_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMs_Mchi500_Mphi995' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-500_Mphi-995_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=995 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

#################### ALL BBbarDM PSEUDOSCALAR

    'bbDMps_Mchi1_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1_Mphi100' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=100 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1_Mphi20' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=20 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=200 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1_Mphi300' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=300 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=50 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=500 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi10_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-10_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi10_Mphi100' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-10_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=100 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi10_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-10_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=50 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi150_Mphi1000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-150_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=1000 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi150_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-150_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=200 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi150_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-150_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=500 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi50_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-50_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=200 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi50_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-50_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=50 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi500_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-500_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=500 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1000_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1000_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=1000 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1_Mphi1000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=1000 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi10_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-10_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi10_Mphi15' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-10_Mphi-15_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=15 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1000_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1000_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=1000 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi1000_Mphi1000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1000_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=1000 GeV m_{#Chi}=1000 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi150_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-150_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi150_Mphi295' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-150_Mphi-295_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=295 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi50_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-50_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi50_Mphi95' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-50_Mphi-95_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=95 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi500_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-500_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi500_Mphi10000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-500_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=10000 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

    'bbDMps_Mchi500_Mphi995' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-500_Mphi-995_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "bbDM m_{#Phi}=995 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

#################### ALL TTbarDM SCALAR

    'ttDMs_Mchi1_Mphi10' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=10 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi1_Mphi20' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=20 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi1_Mphi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=50 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi1_Mphi100' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=100 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi1_Mphi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=200 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi1_Mphi300' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=300 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi1_Mphi500' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=500 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi1_Mphi1000' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=1000 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi10_Mphi10' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-10_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=10 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi10_Mphi100' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-10_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=100 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi10_Mphi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-10_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=50 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

#    'ttDMs_Mchi150_Mphi1000' : {
#        'order' : 1001,
#        'files' : ['TTbarDMJets_scalar_Mchi-150_Mphi-1000_madgraphMLM_pythia8_v1'],
#        'fillcolor' : 623,
#        'fillstyle' : 3005,
#        'linecolor' : 623,
#        'linestyle' : 1,
#        'label' : "ttDM m_{#Phi}=1000 GeV m_{#Chi}=150 GeV",
#        'weight': 1.,
#        'plot': False,
#    },

    'ttDMs_Mchi150_Mphi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-150_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=200 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

#    'ttDMs_Mchi150_Mphi500' : {
#        'order' : 1001,
#        'files' : ['TTbarDMJets_scalar_Mchi-150_Mphi-500_madgraphMLM_pythia8_v1'],
#        'fillcolor' : 623,
#        'fillstyle' : 3005,
#        'linecolor' : 623,
#        'linestyle' : 1,
#        'label' : "ttDM m_{#Phi}=500 GeV m_{#Chi}=150 GeV",
#        'weight': 1.,
#        'plot': False,
#    },

    'ttDMs_Mchi50_Mphi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-50_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=50 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi500_Mphi500' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-500_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=500 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMs_Mchi50_Mphi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-50_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=200 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },


    'ttDMs_Mchi50_Mphi300' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-50_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=300 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

#################### ALL TTbarDM PSEUDOSCALAR

    'ttDMps_Mchi1_Mphi10' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-1_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=10 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi1_Mphi100' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-1_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=100 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi1_Mphi20' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=20 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi1_Mphi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-1_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=200 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi1_Mphi300' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-1_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=300 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi1_Mphi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-1_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=50 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi1_Mphi500' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=500 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi10_Mphi10' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-10_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=10 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi10_Mphi100' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-10_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=100 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi10_Mphi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-10_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=50 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi150_Mphi1000' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-150_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=1000 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi150_Mphi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-150_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=200 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi150_Mphi500' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-150_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=500 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi50_Mphi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-50_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=200 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi50_Mphi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-50_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=50 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi500_Mphi500' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-500_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=500 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDMps_Mchi50_Mphi300' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_pseudoscalar_Mchi-50_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=300 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },
    
#################### ALL HF(bb+tt)DM SCALAR

    'hfDMs_Mchi1_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-1_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=10 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMs_Mchi1_Mphi20' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=20 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMs_Mchi1_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-1_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#Phi}=50 GeV",
        'weight': 1.,
        'plot': True,
    },

    'hfDMs_Mchi1_Mphi100' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-1_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#Phi}=100 GeV",
        'weight': 1.,
        'plot': True,
    },

    'hfDMs_Mchi1_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-1_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#Phi}=200 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMs_Mchi1_Mphi300' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-1_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=300 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMs_Mchi1_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#Phi}=500 GeV",
        'weight': 1.,
        'plot': True,
    },

    'hfDMs_Mchi1_Mphi1000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-1_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-1_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#Phi}=1000 GeV",
        'weight': 1.,
        'plot': True,
    },

    'hfDMs_Mchi10_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-10_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-10_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=10 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMs_Mchi10_Mphi100' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-10_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-10_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=100 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMs_Mchi10_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-10_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-10_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=50 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

#    'hfDMs_Mchi150_Mphi1000' : {
#        'order' : 1001,
#        'files' : ['BBbarDMJets_scalar_Mchi-150_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-150_Mphi-1000_madgraphMLM_pythia8_v1'],
#        'fillcolor' : 623,
#        'fillstyle' : 3005,
#        'linecolor' : 623,
#        'linestyle' : 1,
#        'label' : "DM+h.f. m_{#Phi}=1000 GeV m_{#Chi}=150 GeV",
#        'weight': 1.,
#        'plot': False,
#    },

    'hfDMs_Mchi150_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-150_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-150_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=200 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

#    'hfDMs_Mchi150_Mphi500' : {
#        'order' : 1001,
#        'files' : ['BBbarDMJets_scalar_Mchi-150_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-150_Mphi-500_madgraphMLM_pythia8_v1'],
#        'fillcolor' : 623,
#        'fillstyle' : 3005,
#        'linecolor' : 623,
#        'linestyle' : 1,
#        'label' : "DM+h.f. m_{#Phi}=500 GeV m_{#Chi}=150 GeV",
#        'weight': 1.,
#        'plot': False,
#    },

    'hfDMs_Mchi50_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-50_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-50_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=50 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMs_Mchi500_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_scalar_Mchi-500_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_scalar_Mchi-500_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=500 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },
    
#################### ALL HF(bb+tt)DM PSEUDOSCALAR
    
    'hfDMps_Mchi1_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-1_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=10 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi1_Mphi100' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-1_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=100 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi1_Mphi20' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2','TTbarDMJets_pseudoscalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=20 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi1_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-1_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=200 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi1_Mphi300' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-1_Mphi-300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=300 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi1_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-1_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=50 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi1_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=500 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi10_Mphi10' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-10_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-10_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=10 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi10_Mphi100' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-10_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-10_Mphi-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=100 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi10_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-10_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-10_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=50 GeV m_{#Chi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi150_Mphi1000' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-150_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-150_Mphi-1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=1000 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi150_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-150_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-150_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=200 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi150_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-150_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-150_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=500 GeV m_{#Chi}=150 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi50_Mphi200' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-50_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-50_Mphi-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=200 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi50_Mphi50' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-50_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-50_Mphi-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=50 GeV m_{#Chi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },

    'hfDMps_Mchi500_Mphi500' : {
        'order' : 1001,
        'files' : ['BBbarDMJets_pseudoscalar_Mchi-500_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1','TTbarDMJets_pseudoscalar_Mchi-500_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v2'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "DM+h.f. m_{#Phi}=500 GeV m_{#Chi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },
    
#################### XZH Signals 623 625 628 629 633 634 635 636
    'XZh_M600' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-600_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-600_13TeV-madgraph-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZh_M800' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-800_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-800_13TeV-madgraph-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZh_M1000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1000_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-1000_13TeV-madgraph-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZh_M1200' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1200_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-1200_13TeV-madgraph-v1'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZh_M1400' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1400_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-1400_13TeV-madgraph-v1'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZh_M1600' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1600_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-1600_13TeV-madgraph-v2'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZh_M1800' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1800_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-1800_13TeV-madgraph-v1'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZh_M2000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-2000_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-2000_13TeV-madgraph-v1'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 2000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZh_M2500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-2500_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-2500_13TeV-madgraph-v1'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 2500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZh_M3000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-3000_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-3000_13TeV-madgraph-v1'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 3000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZh_M3500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-3500_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-3500_13TeV-madgraph-v1'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 3500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZh_M4000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-4000_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-4000_13TeV-madgraph-v1'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 4000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZh_M4500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-4500_13TeV-madgraph-v1', 'ZprimeToZhToZinvhbb_narrow_M-4500_13TeV-madgraph-v1'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 4500 GeV",
        'weight': 1.,
        'plot': False,
    },

###

    'XWh_M600' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-600_13TeV-madgraph-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWh_M800' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-800_13TeV-madgraph-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWh_M1000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1000_13TeV-madgraph-v1'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWh_M1200' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1200_13TeV-madgraph-v1'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWh_M1400' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1400_13TeV-madgraph-v1'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWh_M1600' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1600_13TeV-madgraph-v1'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWh_M1800' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1800_13TeV-madgraph-v1'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWh_M2000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-2000_13TeV-madgraph-v1'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 2000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWh_M2500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-2500_13TeV-madgraph-v1'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 2500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWh_M3000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-3000_13TeV-madgraph-v1'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 3000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWh_M3500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-3500_13TeV-madgraph-v1'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 3500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWh_M4000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-4000_13TeV-madgraph-v1'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 4000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWh_M4500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-4500_13TeV-madgraph-v1'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{X} = 4500 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    # Dummy entry for background sum
    'BkgSum' : {
        'order' : 0,
        'files' : [],
        'fillcolor' : 1,
        'fillstyle' : 3003,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "MC Stat",
        'weight': 1.,
        'plot': True,
    },
}


sample['DYJetsToLL_0b'] = sample['DYJetsToLL'].copy()
sample['DYJetsToLL_0b']['fillcolor'] = sample['DYJetsToLL_0b']['linecolor'] = 410
sample['DYJetsToLL_1b'] = sample['DYJetsToLL'].copy()
sample['DYJetsToLL_1b']['fillcolor'] = sample['DYJetsToLL_1b']['linecolor'] = 418
sample['DYJetsToLL_2b'] = sample['DYJetsToLL'].copy()
sample['DYJetsToLL_2b']['fillcolor'] = sample['DYJetsToLL_2b']['linecolor'] = 419

sample['DYJetsToLL_HT_0b'] = sample['DYJetsToLL_HT'].copy()
sample['DYJetsToLL_HT_0b']['fillcolor'] = sample['DYJetsToLL_HT_0b']['linecolor'] = 410
sample['DYJetsToLL_HT_1b'] = sample['DYJetsToLL_HT'].copy()
sample['DYJetsToLL_HT_1b']['fillcolor'] = sample['DYJetsToLL_HT_1b']['linecolor'] = 418
sample['DYJetsToLL_HT_2b'] = sample['DYJetsToLL_HT'].copy()
sample['DYJetsToLL_HT_2b']['fillcolor'] = sample['DYJetsToLL_HT_2b']['linecolor'] = 419

sample['DYJetsToNuNu_0b'] = sample['DYJetsToNuNu'].copy()
sample['DYJetsToNuNu_0b']['fillcolor'] = sample['DYJetsToNuNu_0b']['linecolor'] = 851
sample['DYJetsToNuNu_1b'] = sample['DYJetsToNuNu'].copy()
sample['DYJetsToNuNu_1b']['fillcolor'] = sample['DYJetsToNuNu_1b']['linecolor'] = 861
sample['DYJetsToNuNu_2b'] = sample['DYJetsToNuNu'].copy()
sample['DYJetsToNuNu_2b']['fillcolor'] = sample['DYJetsToNuNu_2b']['linecolor'] = 862

sample['DYJetsToNuNu_HT_0b'] = sample['DYJetsToNuNu_HT'].copy()
sample['DYJetsToNuNu_HT_0b']['fillcolor'] = sample['DYJetsToNuNu_HT_0b']['linecolor'] = 851
sample['DYJetsToNuNu_HT_1b'] = sample['DYJetsToNuNu_HT'].copy()
sample['DYJetsToNuNu_HT_1b']['fillcolor'] = sample['DYJetsToNuNu_HT_1b']['linecolor'] = 861
sample['DYJetsToNuNu_HT_2b'] = sample['DYJetsToNuNu_HT'].copy()
sample['DYJetsToNuNu_HT_2b']['fillcolor'] = sample['DYJetsToNuNu_HT_2b']['linecolor'] = 862

sample['WJetsToLNu_0b'] = sample['WJetsToLNu'].copy()
sample['WJetsToLNu_0b']['fillcolor'] = sample['WJetsToLNu_0b']['linecolor'] = 880
sample['WJetsToLNu_1b'] = sample['WJetsToLNu'].copy()
sample['WJetsToLNu_1b']['fillcolor'] = sample['WJetsToLNu_1b']['linecolor'] = 881
sample['WJetsToLNu_2b'] = sample['WJetsToLNu'].copy()
sample['WJetsToLNu_2b']['fillcolor'] = sample['WJetsToLNu_2b']['linecolor'] = 882

sample['WJetsToLNu_HT_0b'] = sample['WJetsToLNu_HT'].copy()
sample['WJetsToLNu_HT_0b']['fillcolor'] = sample['WJetsToLNu_HT_0b']['linecolor'] = 880
sample['WJetsToLNu_HT_1b'] = sample['WJetsToLNu_HT'].copy()
sample['WJetsToLNu_HT_1b']['fillcolor'] = sample['WJetsToLNu_HT_1b']['linecolor'] = 881
sample['WJetsToLNu_HT_2b'] = sample['WJetsToLNu_HT'].copy()
sample['WJetsToLNu_HT_2b']['fillcolor'] = sample['WJetsToLNu_HT_2b']['linecolor'] = 882



sample['TTbar_0l'] = sample['TTbar'].copy()
sample['TTbar_1l'] = sample['TTbar'].copy()
sample['TTbar_2l'] = sample['TTbar'].copy()


#samplegroups = OrderedDict(sorted(samplegroups.iteritems(), key=lambda x: x[1]['order']))
